FROM golang:1.20-alpine as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o authorization_service .

FROM alpine:latest

copy FROM builder /app/authorization_service 
WORKDIR /app
CMD ["./authorization_service"]