FROM golang:1.21-alpine3.18 as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o authorization_service .

FROM scratch

COPY --from=builder /app/authorization_service /app/authorization_service 
ENTRYPOINT [ "/app/authorization_service" ]